version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  geoserver:
    image: kartoza/geoserver:2.25.2
    restart: always
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_PASSWORD=admin
    volumes:
      - geoserver_data:/opt/geoserver/data_dir

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  postgis_data:
  geoserver_data:
