name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          if [ ! -d "gis-edit-reactapp" ]; then
            echo "Cloning repo..."
            git clone https://github.com/msurya231209/gis-edit-reactapp.git
          else
            echo "Repo already exists. Pulling latest changes..."
            cd gis-edit-reactapp
            git pull origin main
            cd ..
          fi

          cd gis-edit-reactapp
          echo "Installing dependencies..."
          npm install

          echo "Building the React app..."
          npm run build
